### ISSUE TITLE
Message

### ISSUE THREAD

**Issue by SAHILGAWLI** [Quema100/Youtube-Quality-Chrome-Extension#1]
hey, are you down for contribution or it's a personal project ?

**Comment by Quema100** [comment]
It's a personal project.

**Comment by SAHILGAWLI** [comment]
sure

**Comment by SAHILGAWLI** [comment]
just curious, why it doesn't support 720p video quality

**Comment by Quema100** [comment]
We don't support 720p because the quality isn't good enough for an optimal viewing experience.

**Comment by Quema100** [comment]
If needed, please let me know. It can be resolved with just a few lines of code.

**Comment by SAHILGAWLI** [comment]
are you aware of ublock origin browser extension?

**Comment by SAHILGAWLI** [comment]
im trying to understand what is the problem that you are solving through this project

**Comment by Quema100** [comment]
There is no issue with my project; it just doesn’t support that feature. If any issues had come up, I would have already resolved them.

**Comment by Quema100** [comment]
You don't need to understand the problem I'm trying to solve.

**Comment by Quema100** [comment]
> are you aware of ublock origin browser extension?

I know
